// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRRHH.Context;

#nullable disable

namespace WebApiRRHH.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260515071812_InitialCreateWithAuthFixed")]
    partial class InitialCreateWithAuthFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiRRHH.Models.Anticipo", b =>
                {
                    b.Property<int>("IdAnticipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnticipo"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Empleado_idEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlanillaIdPlanilla")
                        .HasColumnType("int");

                    b.Property<int>("Planilla_idPlanilla")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnticipo");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PlanillaIdPlanilla");

                    b.ToTable("Anticipos");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmpleadoAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpleadoEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EmpleadoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("IX_AuditLogs_EmpleadoId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Bono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bonos");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("SueldoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCargo");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("WebApiRRHH.Models.CargoEmpleado", b =>
                {
                    b.Property<int>("IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("CargoIdCargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fechaNombramiento")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCargo", "IdEmpleado");

                    b.HasIndex("CargoIdCargo");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("CargoEmpleado");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Deduccion", b =>
                {
                    b.Property<int>("IdDeduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDeduccion"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TipoDeduccionIdTipoDeduccion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idTipoDeduccion")
                        .HasColumnType("int");

                    b.Property<decimal>("valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDeduccion");

                    b.HasIndex("TipoDeduccionIdTipoDeduccion");

                    b.ToTable("Deducciones");
                });

            modelBuilder.Entity("WebApiRRHH.Models.DeduccionEmpleado", b =>
                {
                    b.Property<int>("IdDeduccion")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeduccionIdDeduccion")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoDeduccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("int");

                    b.Property<int>("PlanillaIdPlanilla")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDeduccion", "IdEmpleado");

                    b.HasIndex("DeduccionIdDeduccion");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PlanillaIdPlanilla");

                    b.ToTable("DeduccionesEmpleados");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("PasswordChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Employee");

                    b.Property<string>("TipoContrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("idEmpleadoJefe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Empleados_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Empleados_IsActive");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Empleados_Role");

                    b.HasIndex("idEmpleadoJefe");

                    b.ToTable("Empleado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 15, 7, 18, 9, 957, DateTimeKind.Utc).AddTicks(8295),
                            DNI = "",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            Name = "Admin",
                            PasswordChangedDate = new DateTime(2026, 5, 15, 7, 18, 9, 957, DateTimeKind.Utc).AddTicks(8297),
                            PasswordHash = "$2a$11$AGIoO2T.SX6GjwDkT5MKeuJ38N3U3bUDg.J27anZGIbKsSOqPuXYy",
                            PhoneNumber = "+504 9999-0000",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 15, 7, 18, 9, 957, DateTimeKind.Utc).AddTicks(8311),
                            DNI = "",
                            Email = "juan.perez@yahoo.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            Name = "Juan",
                            PasswordChangedDate = new DateTime(2026, 5, 15, 7, 18, 9, 957, DateTimeKind.Utc).AddTicks(8312),
                            PasswordHash = "$2a$11$1sLhxL/dAp3p2AmTqifUd.7ozSkVBobtOnvY9DmuZsOA7PUPJdLdu",
                            PhoneNumber = "+504 9999-8888",
                            Role = "Empleado"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 15, 7, 18, 9, 957, DateTimeKind.Utc).AddTicks(8318),
                            DNI = "",
                            Email = "maria.gonzalez@gmail.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            Name = "María",
                            PasswordChangedDate = new DateTime(2026, 5, 15, 7, 18, 9, 957, DateTimeKind.Utc).AddTicks(8319),
                            PasswordHash = "$2a$11$1sLhxL/dAp3p2AmTqifUd.7ozSkVBobtOnvY9DmuZsOA7PUPJdLdu",
                            PhoneNumber = "+504 9999-7777",
                            Role = "Cliente"
                        });
                });

            modelBuilder.Entity("WebApiRRHH.Models.EmpleadoBono", b =>
                {
                    b.Property<int>("Empleado_idEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("Bono_idBono")
                        .HasColumnType("int");

                    b.Property<int>("BonoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanillaIdPlanilla")
                        .HasColumnType("int");

                    b.Property<int>("Planilla_idPlanilla")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Empleado_idEmpleado", "Bono_idBono");

                    b.HasIndex("BonoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PlanillaIdPlanilla");

                    b.ToTable("EmpleadoBonos");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Planilla", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanilla"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEfectiva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlanilla");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("WebApiRRHH.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EmpleadoAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("IX_RefreshTokens_EmpleadoId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("WebApiRRHH.Models.TipoDeduccion", b =>
                {
                    b.Property<int>("IdTipoDeduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDeduccion"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoDeduccion");

                    b.ToTable("TipoDeducciones");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Anticipo", b =>
                {
                    b.HasOne("WebApiRRHH.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiRRHH.Models.Planilla", "Planilla")
                        .WithMany()
                        .HasForeignKey("PlanillaIdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Audit", b =>
                {
                    b.HasOne("WebApiRRHH.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("WebApiRRHH.Models.CargoEmpleado", b =>
                {
                    b.HasOne("WebApiRRHH.Models.Cargo", "Cargo")
                        .WithMany("CargosEmpleados")
                        .HasForeignKey("CargoIdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiRRHH.Models.Empleado", "Empleado")
                        .WithMany("CargosEmpleados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Deduccion", b =>
                {
                    b.HasOne("WebApiRRHH.Models.TipoDeduccion", "TipoDeduccion")
                        .WithMany()
                        .HasForeignKey("TipoDeduccionIdTipoDeduccion");

                    b.Navigation("TipoDeduccion");
                });

            modelBuilder.Entity("WebApiRRHH.Models.DeduccionEmpleado", b =>
                {
                    b.HasOne("WebApiRRHH.Models.Deduccion", "Deduccion")
                        .WithMany()
                        .HasForeignKey("DeduccionIdDeduccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiRRHH.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiRRHH.Models.Planilla", "Planilla")
                        .WithMany()
                        .HasForeignKey("PlanillaIdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deduccion");

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Empleado", b =>
                {
                    b.HasOne("WebApiRRHH.Models.Empleado", "Jefe")
                        .WithMany()
                        .HasForeignKey("idEmpleadoJefe");

                    b.Navigation("Jefe");
                });

            modelBuilder.Entity("WebApiRRHH.Models.EmpleadoBono", b =>
                {
                    b.HasOne("WebApiRRHH.Models.Bono", "Bono")
                        .WithMany()
                        .HasForeignKey("BonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiRRHH.Models.Empleado", "Empleado")
                        .WithMany("EmpleadoBonos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiRRHH.Models.Planilla", "Planilla")
                        .WithMany()
                        .HasForeignKey("PlanillaIdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bono");

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("WebApiRRHH.Models.RefreshToken", b =>
                {
                    b.HasOne("WebApiRRHH.Models.Empleado", "Empleado")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Cargo", b =>
                {
                    b.Navigation("CargosEmpleados");
                });

            modelBuilder.Entity("WebApiRRHH.Models.Empleado", b =>
                {
                    b.Navigation("CargosEmpleados");

                    b.Navigation("EmpleadoBonos");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
