// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRRHH.Context;

#nullable disable

namespace WebApiRRHH.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260410202837_InitialCreateWithAuth")]
    partial class InitialCreateWithAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiRRHH.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("PasswordChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Employee");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 10, 20, 28, 36, 762, DateTimeKind.Utc).AddTicks(764),
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            Name = "Admin",
                            PasswordChangedDate = new DateTime(2026, 4, 10, 20, 28, 36, 762, DateTimeKind.Utc).AddTicks(765),
                            PasswordHash = "$2a$11$VAIs76c.8EHk.xYe4DuF3OphojU0QqvLzNzpysm5dbSOejAikI8BO",
                            PhoneNumber = "+504 9999-0000",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 10, 20, 28, 36, 762, DateTimeKind.Utc).AddTicks(774),
                            Email = "juan.perez@yahoo.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            Name = "Juan",
                            PasswordChangedDate = new DateTime(2026, 4, 10, 20, 28, 36, 762, DateTimeKind.Utc).AddTicks(774),
                            PasswordHash = "$2a$11$7u3QkCJJBwNrgnoH7MNB8epC1QHT.VypVA1bRHeOxDHaa.pvgIxAC",
                            PhoneNumber = "+504 9999-8888",
                            Role = "Empleado"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 10, 20, 28, 36, 762, DateTimeKind.Utc).AddTicks(778),
                            Email = "maria.gonzalez@gmail.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            Name = "María",
                            PasswordChangedDate = new DateTime(2026, 4, 10, 20, 28, 36, 762, DateTimeKind.Utc).AddTicks(779),
                            PasswordHash = "$2a$11$7u3QkCJJBwNrgnoH7MNB8epC1QHT.VypVA1bRHeOxDHaa.pvgIxAC",
                            PhoneNumber = "+504 9999-7777",
                            Role = "Cliente"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
